/**
 * Deno test for WebAssembly build of fpexif
 *
 * This test verifies that the WASM build can:
 * 1. Load and initialize successfully via wasm-bindgen generated bindings
 * 2. Parse a real image file with EXIF data
 * 3. Extract meaningful metadata
 * 4. Output exiftool-compatible JSON for comparison
 *
 * Run with: deno test --allow-read tests/wasm_test.ts
 *
 * To output JSON for exiftool comparison:
 *   deno run --allow-read tests/wasm_test.ts <image_file>
 */

import { assertEquals, assertExists } from "https://deno.land/std@0.224.0/assert/mod.ts";

// Import the generated WASM bindings
// These will be generated by wasm-bindgen in the pkg directory
import init, { parse_exif, parse_exif_json, version } from "../pkg/fpexif.js";

// Check if running as script (not as test)
const isScript = Deno.args.length > 0;

if (isScript) {
  // Script mode: output exiftool-compatible JSON for a single file
  await init();

  const filePath = Deno.args[0];
  const fileData = await Deno.readFile(filePath);

  const json = parse_exif_json(fileData);
  console.log(json);

  Deno.exit(0);
}

Deno.test("WASM - Initialize and get version", async () => {
  // Initialize the WASM module
  await init();

  const ver = version();
  assertExists(ver, "version should exist");
  console.log(`fpexif WASM version: ${ver}`);
});

Deno.test("WASM - Parse RAF file with EXIF data", async () => {
  // Initialize the WASM module
  await init();

  // Read the test RAF file
  const testFilePath = new URL("../test-data/DSCF0062.RAF", import.meta.url);
  const fileData = await Deno.readFile(testFilePath);

  console.log(`Loaded test file: ${fileData.length} bytes`);

  // Parse the EXIF data using wasm-bindgen generated function
  const result = parse_exif(fileData);

  console.log("Parse result:", result);

  // Verify we got a valid JSON result
  const parsed = JSON.parse(result);
  assertExists(parsed, "Should return parsed data");
  assertExists(parsed.tag_count, "Should have tag_count");

  // The RAF file should have at least some EXIF tags
  const tagCount = parsed.tag_count as number;
  assertEquals(tagCount > 0, true, `Should have extracted EXIF tags, got ${tagCount}`);

  console.log(`✓ Successfully parsed ${tagCount} EXIF tags from RAF file`);

  // Verify we have tags
  assertExists(parsed.tags, "Should have tags object");
  console.log(`✓ EXIF tags available: ${Object.keys(parsed.tags).length}`);
});

Deno.test("WASM - Output exiftool-compatible JSON", async () => {
  // Initialize the WASM module
  await init();

  // Read the test RAF file
  const testFilePath = new URL("../test-data/DSCF0062.RAF", import.meta.url);
  const fileData = await Deno.readFile(testFilePath);

  // Parse using exiftool-compatible format
  const json = parse_exif_json(fileData);

  // Verify it's valid JSON array format like exiftool
  const parsed = JSON.parse(json);
  assertEquals(Array.isArray(parsed), true, "Should be an array");
  assertEquals(parsed.length, 1, "Should have one element");

  const tags = parsed[0];
  assertExists(tags, "Should have tags object");

  // Check for some common EXIF fields
  console.log(`✓ Exiftool-compatible JSON with ${Object.keys(tags).length} fields`);

  // Output sample of tags for verification
  const sampleTags = ["Make", "Model", "Software", "DateTimeOriginal", "ExposureTime", "FNumber"];
  for (const tag of sampleTags) {
    if (tags[tag]) {
      console.log(`  ${tag}: ${JSON.stringify(tags[tag])}`);
    }
  }
});
