/**
 * Deno test for WebAssembly build of fpexif
 *
 * This test verifies that the WASM build can:
 * 1. Load and initialize successfully via wasm-bindgen generated bindings
 * 2. Parse a real image file with EXIF data
 * 3. Extract meaningful metadata
 *
 * Run with: deno test --allow-read tests/wasm_test.ts
 */

import { assertEquals, assertExists } from "https://deno.land/std@0.224.0/assert/mod.ts";

// Import the generated WASM bindings
// These will be generated by wasm-bindgen in the pkg directory
import init, { parse_exif, version } from "../pkg/fpexif.js";

Deno.test("WASM - Initialize and get version", async () => {
  // Initialize the WASM module
  await init();

  const ver = version();
  assertExists(ver, "version should exist");
  console.log(`fpexif WASM version: ${ver}`);
});

Deno.test("WASM - Parse RAF file with EXIF data", async () => {
  // Initialize the WASM module
  await init();

  // Read the test RAF file
  const testFilePath = new URL("../test-data/DSCF0062.RAF", import.meta.url);
  const fileData = await Deno.readFile(testFilePath);

  console.log(`Loaded test file: ${fileData.length} bytes`);

  // Parse the EXIF data using wasm-bindgen generated function
  const result = parse_exif(fileData);

  console.log("Parse result:", result);

  // Verify we got a valid JSON result
  const parsed = JSON.parse(result);
  assertExists(parsed, "Should return parsed data");
  assertExists(parsed.tag_count, "Should have tag_count");

  // The RAF file should have at least some EXIF tags
  const tagCount = parsed.tag_count as number;
  assertEquals(tagCount > 0, true, `Should have extracted EXIF tags, got ${tagCount}`);

  console.log(`✓ Successfully parsed ${tagCount} EXIF tags from RAF file`);

  // Verify we have tags
  assertExists(parsed.tags, "Should have tags object");
  console.log(`✓ EXIF tags available: ${Object.keys(parsed.tags).length}`);
});
